apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts
helmCharts:
- releaseName: nodeapp
  namespace: dev
  name: nodeapp
  valuesFile: values.yaml
  # valuesInline:
  #   ingress:
  #     enabled: true

namespace: base
