
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
labels:
- includeSelectors: true
  pairs:
    env: dev

nameSuffix: -dev
namespace: dev

helmGlobals:
  chartHome: ../../charts
helmCharts:
- name: nodeapp
  valuesFile: values-app.yaml
  namespace: dev

patches:
- patch: |-
    - op: replace
      path: "/spec/template/spec/containers/0/env/5"
      value:
        name: SERVICENAME
        value: mongo-dev
    - op: replace
      path: "/spec/serviceName"
      value: "mongo-dev"
    - op: replace
      path: "/spec/replicas"
      value: 1
  target:
    kind: StatefulSet
    name: mongo
- patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: nodeapp-dev.local
  target:
    kind: Ingress
    name: nodeapp